var data = [1]//, 2, 3, 4]

var svgWidth = 290, svgHeight = 100, lineWidth = 10

var svg = d3.select("svg")
  .attr("width", svgWidth)
  .attr("height", svgHeight)

svg.selectAll("rect")
  .data(data)
  .enter()
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight)
  .attr("width", lineWidth)
  .attr("transform", "translate(5, 0)")

d3.select("svg")
  .append("rect")
  .attr("y", 10)
  .attr("height", svgHeight / 1.5)
  .attr("width", lineWidth)
  .attr("transform", "translate(0, 0) rotate(-45)")

  d3.select("svg")
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight / 1.5)
  .attr("width", lineWidth)
  .attr("transform", "translate(95, 0) rotate(45)")

  d3.select("svg")
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight)
  .attr("width", lineWidth)
  .attr("transform", "translate(95, 0)")

  d3.select("svg")
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight)
  .attr("width", lineWidth)
  .attr("transform", "translate(120, 0)")

  d3.select("svg")
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight)
  .attr("width", lineWidth)
  .attr("transform", "translate(145, 0)")

  d3.select("svg")
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight / 1.5)
  .attr("width", lineWidth)
  .attr("transform", "translate(192, 0) rotate(45)")

  d3.select("svg")
  .append("rect")
  .attr("y", 75)
  .attr("height", svgHeight / 1.5)
  .attr("width", lineWidth)
  .attr("transform", "translate(95, 0) rotate(-45)")

  d3.select("svg")
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight)
  .attr("width", lineWidth)
  .attr("transform", "translate(215, 0)")

  d3.select("svg")
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight / 1.5)
  .attr("width", lineWidth)
  .attr("transform", "translate(215, 10) rotate(-90)")

  d3.select("svg")
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight / 2.5)
  .attr("width", lineWidth)
  .attr("transform", "translate(215, 55) rotate(-90)")

  d3.select("svg")
  .append("rect")
  .attr("y", 0)
  .attr("height", svgHeight / 1.5)
  .attr("width", lineWidth)
  .attr("transform", "translate(215, 100) rotate(-90)")